### ISSUE TITLE
layers

### ISSUE THREAD

**Issue by echobytes17** [HITSZ-HLT/JointCL#1]
Hi ,can you share the complete  gnn_layer code.Thank you very much!

**Comment by HLT-HITSZ** [comment]
Thanks for pointing this out! The complete layers code has been uploaded.

**Comment by echobytes17** [comment]
![image](https://user-images.githubusercontent.com/86192455/160042337-06c062c0-e48f-4a02-b070-69cb9243ae28.png)
I reproduced your article 'JointCL: A Joint Contrastive Learning Framework for Zero-Shot Stance Detection', why the f1-score for the label 1 is zero, can you help me with this?

**Comment by South7X** [comment]
> ![image](https://user-images.githubusercontent.com/86192455/160042337-06c062c0-e48f-4a02-b070-69cb9243ae28.png) I reproduced your article 'JointCL: A Joint Contrastive Learning Framework for Zero-Shot Stance Detection', why the f1-score for the label 1 is zero, can you help me with this?

The problem will no longer exist when changing some training settings. For example, try a different seed like 42.
