### ISSUE TITLE
The results of vast

### ISSUE THREAD

**Issue by Wenze7** [HITSZ-HLT/JointCL#5]
I have tried your project in vast, and I haven't made any changes. I got the following results, are these results as expected?

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/55132749/194689624-a9fd9ba7-c339-4f33-83c0-bad9eea78701.png">

**Comment by BinLiang-NLP** [comment]
> I have tried your project in vast, and I haven't made any changes. I got the following results, are these results as expected?
> 
> <img alt="image" width="1193" src="https://user-images.githubusercontent.com/55132749/194689624-a9fd9ba7-c339-4f33-83c0-bad9eea78701.png">

Hi, we have fixed the problems. Please use "_git pull_" to update the code. We also provide checkpoints that are superior to the reported results for testing.
For the VAST dataset, the performance gap within 2% is natural. Please use different seeds to obtain better performance.
Please let me know if there is any problem.
Thanks a lot!
