### ISSUE TITLE
The result of model

### ISSUE THREAD

**Issue by clearpeck** [HITSZ-HLT/JointCL#6]
![1667890263118](https://user-images.githubusercontent.com/73450556/200495277-9db03bff-965e-4056-80a7-5c59c0b38059.jpg)
![1667890301570](https://user-images.githubusercontent.com/73450556/200495286-427a0564-b302-4eb7-b306-d8761f23cc1c.jpg)
![1667890327031](https://user-images.githubusercontent.com/73450556/200495299-e1046e5d-480d-4694-8caf-0b964ca11bf5.jpg)
![1667890350763](https://user-images.githubusercontent.com/73450556/200495309-ec5bd32c-17ff-43b2-a856-47294d8bbf17.jpg)
![1667890377895](https://user-images.githubusercontent.com/73450556/200495317-a5de568f-7a2b-4f0a-9890-cfc2ecf78054.jpg)
![1667890447902](https://user-images.githubusercontent.com/73450556/200495323-47822c2b-e685-4dfc-870b-5c921dbb8943.jpg)
![1667890531426](https://user-images.githubusercontent.com/73450556/200495380-d188495c-5bf6-4ce4-bfe6-fbca370c2eb3.jpg)
For the doubt of the experimental results, the experimental results are too different. I have tried various combinations of  hyper-parameters. What is the reason?

**Comment by clearpeck** [comment]
In addition, TOAD needs a lot of unlabeled data based on test topics to train topic discriminators. The author uses TOAD to do experiments on VAST and WT-WT datasets without unlabeled data. Is this setting reasonable?

**Comment by BinLiang-NLP** [comment]
> ![1667890263118](https://user-images.githubusercontent.com/73450556/200495277-9db03bff-965e-4056-80a7-5c59c0b38059.jpg) ![1667890301570](https://user-images.githubusercontent.com/73450556/200495286-427a0564-b302-4eb7-b306-d8761f23cc1c.jpg) ![1667890327031](https://user-images.githubusercontent.com/73450556/200495299-e1046e5d-480d-4694-8caf-0b964ca11bf5.jpg) ![1667890350763](https://user-images.githubusercontent.com/73450556/200495309-ec5bd32c-17ff-43b2-a856-47294d8bbf17.jpg) ![1667890377895](https://user-images.githubusercontent.com/73450556/200495317-a5de568f-7a2b-4f0a-9890-cfc2ecf78054.jpg) ![1667890447902](https://user-images.githubusercontent.com/73450556/200495323-47822c2b-e685-4dfc-870b-5c921dbb8943.jpg) ![1667890531426](https://user-images.githubusercontent.com/73450556/200495380-d188495c-5bf6-4ce4-bfe6-fbca370c2eb3.jpg) For the doubt of the experimental results, the experimental results are too different. I have tried various combinations of hyper-parameters. What is the reason?

Hi, I apologize for the inconvenience.
We have fixed the problems. Please run "_git pull_" to update the code.
Please tune the parameter "_--seed_" for better performance since the small dataset.
Please let me know if there is any problem.
Thank you!!!

**Comment by BinLiang-NLP** [comment]
> In addition, TOAD needs a lot of unlabeled data based on test topics to train topic discriminators. The author uses TOAD to do experiments on VAST and WT-WT datasets without unlabeled data. Is this setting reasonable?

Hi, we use the open-source code of TOAD to conduct experiments on VAST and WT-WT datasets. 
We do agree that using the unlabeled data may lead to better performance of TOAD. 
However, for VAST and WT-WT datasets, there are no corresponding unlabeled data and keywords. 
Therefore, we conducted a comparative experiment on the SEM16 dataset by using or removing the unlabeled data, and found that the performance gap is mostly within 5%, so the results on VAST and WT-WT datasets are overall reasonable.
